### PR TITLE
Changed Timeformat: Display seconds on long duration (>3600s)

### PR DESCRIPTION
**Pull request by rekinyz**
formatTime(3891) = 1h4m51s

### CODE REVIEW

**Comment by AndiDittrich** [comment]
hi rekinyz,

i'm not shure if we should change this...it was a "by design" decision to hide seconds on long duration (not even needed) - why you want to change it ?

btw. i've changed the issue name

best regards, Andi

**Comment by rekinyz** [comment]
Hi Andi,

I am using this lib for displaying the export progress. Some of my exports will take hours. But with the old function, formatTime(3691) = 1h1.5166666666666666m. I think if you just don't want to display the seconds, you still need to round the minutes.

best regards,
rekinyz

**Comment by AndiDittrich** [comment]
now i understand your issue :) 

it is caused by a "wrong" call of the `Bar.prototype.formatTime` function. the second parameter `roundTo` was not set for **elapsedTime** calculation. i will fix it now

**Comment by AndiDittrich** [comment]
should be fixed, please try it

**Comment by rekinyz** [comment]
danke, es hat funktioniert :+1:

**Comment by AndiDittrich** [comment]
alles klar, dann schließe ich den pull-request und werde die neue version vorraussichtlich heute freigeben

**Pull request closed without merging**
