### PR TITLE
Add emptyOnZero option to display total:0 bars as empty, not full

### PR DESCRIPTION
**Pull request by nickcmaynard**
... also add devDependencies so `npm run test` works.

### CODE REVIEW

**Comment by AndiDittrich** [comment]
Hi @nickcmaynard 

i'll check this soon - there were a few reasons in the past to set the value to `1.0`

**Comment by nickcmaynard** [comment]
Great stuff - thanks.  This defaults to current behaviour, so I hope this should be fairly low impact.

**Comment by AndiDittrich** [comment]
in which cases does the unexpected behaviour appear ? 
i can only reproduce the `1.0` fallback in case `total` is set to 0:

### Example 1 - total=100 ###
```js
const b1 = new _progress.Bar();
b1.start(100, 0);
```

```raw
 $ node dev.js 
progress [----------------------------------------] 0% | ETA: 0s | 0/200
```

### Example 1 - total=0 ###
```js
const b1 = new _progress.Bar();
b1.start(0, 0);
```

```raw
 $ node dev.js 
progress [========================================] 100% | ETA: 0s | 0/0
```

**Comment by nickcmaynard** [comment]
> in which cases does the unexpected behaviour appear ?
> i can only reproduce the `1.0` fallback in case `total` is set to 0:

Yes - precisely this case.  My use case pre-initialises a number of progress bars - "stages" - but the size of those stages isn't known until later in the execution.

Now, I could pre-inititialise `total` to a non-zero value, but that would erroneously imply it's correct.

Thank you for merging :)

**Comment by AndiDittrich** [comment]
ok, i've never projected such use case

**Pull request merged**
